Update install script to update npm

diff --git a/exe/setup b/exe/setup
--- a/exe/setup
+++ b/exe/setup
@@ -16,6 +16,7 @@ pass() {
 fail() {
   echo
   echo "$(tput setaf 1)    FAIL: $1 $(tput sgr0)"
+  exit 1
 }
 
 warn() {
@@ -47,50 +48,52 @@ if hash npm 2>/dev/null; then
   pass "npm is installed"
 else
   fail "no npm executable found"
-  exit 1
+fi
+sep
+
+echo "Updating npm..."
+if npm install -g npm@latest; then
+  pass "npm successfully updated"
+else
+  fail "npm could not be updated"
 fi
 sep
 
 echo "Installing gulp..."
 if npm install -g gulp; then
-  pass "gulp installed"
+  pass "gulp successfully installed"
 else
   fail "gulp could not be installed"
-  exit 1
 fi
 sep
 
 echo "Installing bower..."
 if npm install -g bower; then
-  pass "bower installed"
+  pass "bower successfully installed"
 else
   fail "bower could not be installed"
-  exit 1
 fi
 sep
 
 echo "Installing babel..."
 if npm install -g babel; then
-  pass "babel installed"
+  pass "babel successfully installed"
 else
   fail "babel could not be installed"
-  exit 1
 fi
 sep
 
 echo "Installing bower components..."
 if bower install > /dev/null; then
-  pass "bower components installed"
+  pass "bower components successfully installed"
 else
   fail "bower components could not be installed"
-  exit 1
 fi
 sep
 
 echo "Installing npm components..."
 if npm install; then
-  pass "bower components installed"
+  pass "npm packages successfully installed"
 else
-  fail "bower components could not be installed"
-  exit 1
+  fail "npm packages could not be installed"
 fi
